### ISSUE TITLE
No Advanced Sleep Analysis data

### ISSUE THREAD

**Issue by afolarin** [btroia/basis-data-export#12]
Doesn't capture the Advanced Sleep Analysis data... i.e
http://www.mybasis.com/wp-content/uploads/2014/01/Basis_Web_Sleep_Dashboard.png

But otherwise still works.

**Comment by bean-s** [comment]
any news on this front? i saw a section in the single day download that looked like it was supposed to have this info in there, but it was blank... (method 1)

**Comment by btroia** [comment]
The script should generate a separate file for each day with a '-sleep.[format]', which contains all of the sleep events/details.

**Comment by bean-s** [comment]
it did work with method 2 for me, but the problem is still that i don't get info about when the different stages of sleep started/stopped (just how much light/deep/REM and when the overall sleep started/stopped); i.e. where is (or do they even allow access to) the data that would allow one to reconstruct the graph in the above linked png?
