### ISSUE TITLE
Multiple days exporting data

### ISSUE THREAD

**Issue by berdesos** [btroia/basis-data-export#18]
Hello!
How do you export data from multiple days, e.g. 2015-06-23 to 2015-06-27 ?
Thank you!

**Comment by btroia** [comment]
You should be able to use the curl method to grab all data from your range of dates as follows:

`curl http://localhost/basis-data-export/basisdataexport.php?date=2015-06-[23-27]`

**Comment by bean-s** [comment]
i know this is noob, but i've spent a couple days on it already because it's the first time i've actually typed anything into the terminal's command line; i try this function and the http one and can't get either to work. instead, i see the script reiterated (in this case five times) and there's no output.  i have the files in my localhost folder, but i don't understand why they're just showing the script instead of running it... could it be a permissions thing?  i'm not an admin user at the moment...
thanks for any two cents...
